name: Release

# Only trigger this action when a new release is published
on:
  release:
    types: [published]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      # Setup the workflow to use the specific version of Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Cleans up unreachable Git objects and convert a shallow clone to a regular one if needed
      - name: Unshallow
        run: git fetch --prune --unshallow
      # Run tests prior to release    
      - name: Test
        run: make test
      # Publish the binaries
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
